### PR TITLE
Use hardcoded port for WebSockets in development.

### LINKED ISSUE #378: Websocket connection stalls forever when running in dev
It seems that commit 569f3753cc688465b8b7cdd27e98b478bd3c36f7 has introduced a bug where connecting to the websocket stalls forever and the "connecting to server" window never goes away. The connection eventually errors out after 2 minutes (timeout) or in rare cases gets through.

Error

The network tab shows that the connection is just pending
image

The commit before (61c94b81d4efbb81dc18827d02cb5e8989eff090) seems to work just fine though.

Steps to reproduce:
* checkout into 569f3753cc688465b8b7cdd27e98b478bd3c36f7 (or master)
* run `yarn start`

### PR DESCRIPTION
**Pull request by jimmycuadra**
Create React App's proxy feature hasn't worked consistently for Dim.
This change returns to the earlier behavior of hardcoding the port used
to establish WebSocket connections in the development environment.

Fixes #378.

### CODE REVIEW

File: ui/src/actions/ws.ts [hunk 1]
```diff
@@ -21,6 +21,9 @@ export const wsConnect =
     const webSocketUrl = (() => {
       const url = new URL("/ws", window.location.href);
       url.protocol = url.protocol.replace("http", "ws");
+      if (process.env.NODE_ENV === "development") {
```
Comment (vgarleanu) [inline ui/src/actions/ws.ts:24]: Id also add a note here stating why we are doing this.

Comment (jimmycuadra) [reply ui/src/actions/ws.ts:26]: Done!
