### PR TITLE
Change session to be based off of UserID instead of Username

### LINKED ISSUE #375: Username changes are not reflected in UI
**Describe the bug**
When you change your username, subsequent requests fail and the old username is displayed.

**To Reproduce**

1. Start brand new install of Dim with a fresh database
2. Register an admin account
3. Go to "Preferences > Profile > Username" and change username.
4. A PATCH request is made to `/api/v1/auth/username` and it returns status code 200.
5. Running `SELECT * FROM users;` in sqlite shows the new username.
6. A GET request is made to `/api/v1/auth/whoami` and it returns status code 200. The response body contains the old username, e.g.:
   ```json
   {"picture":null,"roles":["owner"],"spentWatching":0,"username":"oldusername"}
   ```
7. Refreshing the page and clicking "Profile" shows the old username in the UI.
8. Two GET requests are made to `/api/v1/user/settings` and both return status code 500 with this body:
   ```json
   {"error":"DatabaseError","messsage":"A database error occured: DatabaseError(RowNotFound)"}
   ```
9. Sticking some `dbg!` statements in `dim::routes::settings::get_user_settings` and hitting `/api/v1/user/settings` via curl reveals this error in the server logs:
   ```
   [dim/src/routes/settings.rs] &User::get(&mut tx, &user.0.claims.get_user()).await = Err(
       DatabaseError(
           RowNotFound,
       ),
   )
   ```
   Perhaps the authentication token used by the client is not being updated after changing usernames?

**Expected behavior**
The new username should be reflect in the UI after reloading the page, and API requests should not return status code 500.

**Device and browser including versions:**
Firefox 95.0.2.

### PR DESCRIPTION
**Pull request by cobyge**
This is in response to and closes #375.  It ended up being a bigger commit than I wanted, here is a summary of the changes:

At a high level - Changing the entire authentication platform to be based off of a unique non-changeable UserID instead of a Username.  The way I chose to do with was by changing the JWT token to be an encrypted UserID.  This also meant that the authentication process is much more database oriented (As every request needs to get all it's information from the database).
* Moving the auth crate into the database crate - All auth functions are now database related, so we needed functions from the database crate (And really, it didn't make much sense to me to have these separate).
* Upgrading the SQLX version - It was hardcoded at `0.5.5`, now upgraded to `0.5.13`
* Changed almost all functions to take a UserID instead of a username.
* The Auth Wrapper now holds a `User` object, retrieved from the DB for each needed request (There may be a better way to do this, but I don't think this is a performance issue - if it is, we can try a caching solution)
* Added a refresh after changing your username, so that the UI updates
* Updated the database schema to support IDs.  This is a breaking change, although it probably wouldn't be too hard to put together a migration script.  Let me know if it's needed.

This is a huge change (Although 95% of it is just changing parameters from Strings to UserIDs), so let me know if you have any feedback or questions

### CODE REVIEW

File: database/src/auth.rs [hunk 1]
```diff
@@ -0,0 +1,152 @@
...
+    let (nonce, cipher) = data.split_at(NONCE_LEN);
+    let aead = Aes256Gcm::new(GenericArray::from_slice(get_key()));
+    let plaintext = aead
+        .decrypt(GenericArray::from_slice(nonce), cipher)
+        .map_err(|_| AuthError::DecryptError)?;
+
+    Ok(UserID(i64::from_be_bytes(plaintext.try_into().unwrap())))
+}
+
+#[cfg(feature = "null_auth")]
```
Comment (vgarleanu) [inline database/src/auth.rs:112]: While we are at it, we should get rid of this feature.

File: database/src/progress.rs [hunk 2]
```diff
@@ -41,29 +42,31 @@ impl Progress {
...
             uid,
             mid
         )
         .fetch_optional(&mut *conn)
         .await?
         .unwrap_or(Self {
+            id: Default::default(),
             media_id: mid,
             user_id: uid,
-            ..Default::default()
```
Comment (vgarleanu) [inline database/src/progress.rs:60]: Keeping this is imo cleaner than specifying each field.

File: database/src/user.rs [hunk 3]
```diff
@@ -98,11 +134,52 @@ pub enum Role {
     User,
 }
 
+#[derive(Copy, Clone, Debug, Deserialize, Eq, PartialEq, Serialize, sqlx::Type)] // Does this need to be clone?
+#[sqlx(transparent)]
+pub struct UserID(pub(crate) i64);
+
+#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq)]
+pub struct Roles(pub Vec<String>);
```
Comment (vgarleanu) [inline database/src/user.rs:142]: Wonder if it's possible for this to be a enum. I haven't thought yet about how permissions will work in the future, so we can leave like this for now, but it's still something we should think about

File: database/src/user.rs [hunk 4]
```diff
@@ -272,21 +397,18 @@ impl InsertableUser {
...
 
         let password = hash(username.clone(), password);
-        let roles = roles.join(",");
-        let prefs = serde_json::to_vec(&prefs).unwrap_or_default();
 
-        sqlx::query!(
-            "INSERT INTO users (username, password, prefs, claimed_invite, roles) VALUES ($1, $2, $3, $4, $5)",
+        let user = sqlx::query_as!(
+            User,
+            r#"INSERT INTO users (username, password, prefs, claimed_invite, roles) VALUES ($1, $2, $3, $4, $5) returning id as "id: UserID",username,roles as "roles: Roles",prefs as "prefs: UserSettings",picture"#,
```
Comment (vgarleanu) [inline database/src/user.rs:403]: Ooh, completely forgot returning statements are now supported in sqlite.

File: ui/src/actions/user.js [hunk 5]
```diff
@@ -88,6 +88,7 @@ export const changeUsername = (newUsername) => async (dispatch, getState) => {
         msg: "Your username has now been updated.",
       })
     );
+    window.location.reload();
```
Comment (vgarleanu) [inline ui/src/actions/user.js:91]: Not a fan of this. We should update our state without having to refresh the whole page.

File: database/src/auth.rs [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+    BadBase64,
+    ShortData,
+    DecryptError,
+    CookieError,
+}
+
+impl warp::reject::Reject for AuthError {}
+
+/// Function encrypts a UserID with a nonce and returns it as a base64 string to be used as a cookie/token.
+pub fn user_cookie_generate(user: UserID) -> String {
```
Comment (vgarleanu) [inline database/src/auth.rs:67]: Some tests for the cookie functions would be nice.

**Review by vgarleanu — COMMENTED** [review]
Looks good so far. I've left some comments on things that caught my eye so far. I'll give this a better review tomorrow morning.

File: database/Cargo.toml [hunk 7]
```diff
@@ -21,19 +22,24 @@ tracing-log = "0.1.2"
 tracing = "0.1.29"
 
 ring = "^0.16.11"
-base64 = "0.13.0"
 uuid = { version = "0.8.1", features = ["v4"] }
 cfg-if = "1.0.0"
 err-derive = "0.3.0"
-sqlx = { version = "=0.5.5", features = ["runtime-tokio-rustls"] }
+sqlx = { version = "=0.5.13", features = ["runtime-tokio-rustls"] }
```
Comment (vgarleanu) [inline database/Cargo.toml:28]: I'm kind of surprised updating to the latest sqlx version worked as last time I attempted it their proc macros started misbehaving.

File: database/migrations/20210619211347_dim.sql [hunk 8]
```diff
@@ -132,7 +132,8 @@ CREATE TABLE mediafile (
 );
 
 CREATE TABLE users (
-    username TEXT PRIMARY KEY,
```
[the remark this answers is not in the document]
Comment (cobyge) [reply database/migrations/20210619211347_dim.sql:135]: I feel like keeping usernames as primary keys is ripe for future mistakes. Using unchangeable integers as the primary key is a guarantee that you will never have a collision.

[the remark this answers is not in the document]
Comment (cobyge) [reply database/migrations/20210619211347_dim.sql:135]: If you prefer to keep usernames, I could try that while adding a non primary-key ID for uniquiness

File: database/src/progress.rs (hunk 2 above)
Comment (cobyge) [reply database/src/progress.rs:60]: My thought behind this is that I don't want to derive Default for`UserID`, as currently only valid IDs can be built, and deriving Default would give us invalid IDs. There isn't any way to partially derive Debug, so this is the closest I could get

File: ui/src/actions/user.js (hunk 5 above)
Comment (cobyge) [reply ui/src/actions/user.js:91]: I have zero frontend experience, this was the closest thing that worked for me. 
If you want, I can leave this out, and you can fix it separately (or just push to this branch), or if you'd like to point me in the right direction, I could try to figure it out

File: database/migrations/20210619211347_dim.sql (hunk 8 above)
[the remark this answers is not in the document]
Comment (vgarleanu) [reply database/migrations/20210619211347_dim.sql:135]: Nope, you're right. Let's leave it like this. Integer primary keys are also probably a lot more efficient.

File: database/src/progress.rs (hunk 2 above)
Comment (vgarleanu) [reply database/src/progress.rs:60]: Sounds good.

File: ui/src/actions/user.js (hunk 5 above)
Comment (vgarleanu) [reply ui/src/actions/user.js:91]: Let's omit this unless you want to give it a try. I've been meaning to convert the sidebar to use RTKQ anyway which would mean you'd have to basically call a `refetch` function.

File: database/src/asset.rs [hunk 9]
```diff
@@ -1,4 +1,4 @@
-use crate::DatabaseError;
+use crate::{user::UserID, DatabaseError};
```
[the remark this answers is not in the document]
Comment (cobyge) [reply database/src/asset.rs]: Done

File: database/src/auth.rs (hunk 1 above)
Comment (cobyge) [reply database/src/auth.rs]: Done

File: ui/src/actions/user.js (hunk 5 above)
Comment (cobyge) [reply ui/src/actions/user.js]: I attempted to fix this, take a look and let me know if you like the other implementation.  If not, I'll remove it and let someone else take care of it.

File: database/src/auth.rs (hunk 6 above)
Comment (cobyge) [reply database/src/auth.rs:66]: Done

File: ui/src/actions/user.js [hunk 10]
```diff
@@ -53,48 +53,50 @@ export const fetchUser = () => async (dispatch, getState) => {
...
+        "Content-Type": "application/json",
+        authorization: token,
+      },
+      body: JSON.stringify({
+        new_username: newUsername,
+      }),
+    };
+
+    try {
+      const res = await fetch("/api/v1/auth/username", config);
```
Comment (vgarleanu) [inline ui/src/actions/user.js:74]: I don't think there is a need to fetch the username again if we make the request for changing a username return the updated username. At that point we need to simply dispatch it.

Comment (cobyge) [reply ui/src/actions/user.js:74]: I'm not sure I understand what you meant.
This is the PATCH request to change the username, it doesn't return the username.

File: database/src/user.rs (hunk 3 above)
Comment (cobyge) [reply database/src/user.rs:146]: I had that thought, but it might be much more difficult to handle client side if it were a bitfield (On second thought - Does client-side even care about roles? If not, I guess it'd be pretty easy)

Comment (vgarleanu) [reply database/src/user.rs:146]: It will in the future. Based on the roles we will disable certain UI elements.

File: ui/src/actions/user.js (hunk 10 above)
Comment (cobyge) [reply ui/src/actions/user.js:74]: I feel like I'm missing something regarding how this should work in the frontend. (Why should the server return the username if I already have it?).
I'll remove this for now.

Comment (vgarleanu) [reply ui/src/actions/user.js:74]: That's a good point. I guess we can do that as well. Since we already have the username we can just set it after the patch request succeeds.

Comment (cobyge) [reply ui/src/actions/user.js:74]: Isn't that what I'm doing in the code?

Comment (vgarleanu) [reply ui/src/actions/user.js:74]: Yep, for some reason I misread the code and thought you were fetching the username again after the patch. My bad, slow mornings.

This LGTM but I will give this a spin locally just in case :).

File: database/migrations/20210619211347_dim.sql [hunk 11]
```diff
@@ -132,7 +132,8 @@ CREATE TABLE mediafile (
...
+    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
```
Comment (vgarleanu) [inline database/migrations/20210619211347_dim.sql:135]: I wonder if its a good idea to turn all of these changes into proper migrations as running the code behind this PR requires you to delete the DB and start from scratch.

**Comment by vgarleanu** [comment]
I've pushed a quick commit which fixes the proxy middleware. The commit also fixes a issue when changing username in the UI where redux would error out that when dispatching `CHANGE_USERNAME_ERR` the payload is not serializable. Stringifying the error seems to get rid of it for now but I'm like 80% sure this is wrong.

This should hopefully not cause any issues until we transition all the old API queries and reducers to RTKQ.

**Comment by vgarleanu** [comment]
At the moment the only blocker for this PR is how to deal with the changes made to the migrations. Ideally we should write a migration script which changes the tables by creating a new table, moving all the rows from the old table into the new one, then rename it.

Migrating the progress table might not be worth it, but ideally I'd want to at least preserve registered users to avoid confusion.

File: database/migrations/20210619211347_dim.sql (hunk 11 above)
Comment (cobyge) [reply database/migrations/20210619211347_dim.sql:135]: I'll take a look at the migration logic tomorrow, but meanwhile:
Adding a file in the migrations folder which transitions the database to the new format while keeping all data should be enough to quietly update all users with older databases?

Comment (cobyge) [reply database/migrations/20210619211347_dim.sql:135]: So I took a look at the migrations:
I've written a migration that keeps the user and progress table, but it turns out that the migration in master is incompatible with the migration from the last release.
I believe this is because in commit 2f94d8f9f38fe27c1aba87a9fc0fa5ad844598fa the file [database/migrations/20210619211347_dim.sql](https://github.com/Dusk-Labs/dim/commit/2f94d8f9f38fe27c1aba87a9fc0fa5ad844598fa#diff-2bc028222faea2098fd3a1370a5e96b102408cedf5fac7b5459d87799db5ec45) was updated.

This could be fixed with another migration, but it means that for now, all the migrations are useless.

Comment (cobyge) [reply database/migrations/20210619211347_dim.sql:135]: Looks like [database/migrations/20210619211347_dim.sql](https://github.com/Dusk-Labs/dim/commit/91088cbba158ee59cc81b8713fa249e2645abb02#diff-2bc028222faea2098fd3a1370a5e96b102408cedf5fac7b5459d87799db5ec45) was pushed since the last release

Comment (vgarleanu) [reply database/migrations/20210619211347_dim.sql:135]: That migration shouldn't really affect the users much, it was done for performance reasons and could be fixed with a separate PR.

> Adding a file in the migrations folder which transitions the database to the new format while keeping all data should be enough to quietly update all users with older databases?

Yes, I believe this is enough, you can create a new migration with `sqlx-cli`. Since we are changing the primary key of a table, I'm not sure if we can simply drop a column, or add a new column in. So i think we will have to re-create the whole table. I am still unsure if its worth it but it'd be a good idea to get into the habit of thinking about migrations even if dim doesnt have many users yet.

Comment (vgarleanu) [reply database/migrations/20210619211347_dim.sql:135]: I think since the last release was simply a candidate we can get away with breaking backwards compatibility and ship a notice saying that the old database has to be removed. Not ideal but has to be done i guess.

Comment (cobyge) [reply database/migrations/20210619211347_dim.sql:135]: I've pushed a commit just now which migrates the `users` and `progress` tables.
It also undoes the two changes in the commits specified above (2f94d8f9f38fe27c1aba87a9fc0fa5ad844598fa and 91088cbba158ee59cc81b8713fa249e2645abb02), and adds them in as a separate migration.
I've tested a migration from the latest release(rc6), and it worked, saving both the users and their progress.

File: database/migrations/20220512200302_add-userid.sql [hunk 12]
```diff
@@ -0,0 +1,68 @@
...
+
+    PRIMARY KEY (id),
+    FOREIGN KEY(media_id) REFERENCES _tblmedia (id) ON DELETE CASCADE ON UPDATE CASCADE,
+    FOREIGN KEY(user_id) REFERENCES old_users(username) ON DELETE CASCADE
+);
+
+INSERT INTO old_progress (id, user_id, delta, media_id, populated) SELECT * FROM progress;
+
+DROP TABLE users;
+DROP TABLE progress;
```
Comment (vgarleanu) [inline database/migrations/20220512200302_add-userid.sql:31]: Looking at the SQlite3 docs, sqlite supports ```ALTER TABLE RENAME TO``` queries. I think we can just use that to rename the table to `old_table`, then create a new table and do the insertion

File: database/migrations/20220512210542_master-changes.sql [hunk 13]
```diff
@@ -0,0 +1,28 @@
...
+CREATE VIEW media AS
+SELECT _tblmedia.*, pp.local_path as poster_path, bp.local_path as backdrop_path
+FROM _tblmedia
+LEFT OUTER JOIN assets pp ON _tblmedia.poster = pp.id
+LEFT OUTER JOIN assets bp ON _tblmedia.backdrop = bp.id;
+CREATE TRIGGER media_delete
+INSTEAD OF DELETE ON media
+BEGIN
+    DELETE FROM _tblmedia WHERE _tblmedia.id = old.id;
+END;
```
Comment (vgarleanu) [inline database/migrations/20220512210542_master-changes.sql:13]: This is a bit unreadable, we should add some blank lines in between sql statements. I think we should stick to 1 blank line in between statements.

Comment (cobyge) [reply database/migrations/20220512210542_master-changes.sql]: Better?

Comment (vgarleanu) [reply database/migrations/20220512210542_master-changes.sql]: yep, looks a lot better.

File: database/migrations/20210619211347_dim.sql (hunk 11 above)
Comment (vgarleanu) [reply database/migrations/20210619211347_dim.sql]: Looks good, ended up being simpler than i initially thought.

**Comment by vgarleanu** [comment]
This PR looks good to me! Will give this another spin tomorrow morning, and hopefully get it merged in if no issues arise!
